#
# ░█▀▀░█░█░▀█▀░█░█░█▀█░█▀█░█▀▀               
# ░▀▀█░█▀█░░█░░█▀▄░█▀█░█░█░█▀▀               
# ░▀▀▀░▀░▀░▀▀▀░▀░▀░▀░▀░▀░▀░▀▀▀               
# ░█▄█░█▀█░█▀█░▀█▀░▀█▀░█▀█░█▀▄░░░█▀█░█▀▄░█▀█░█▀▀░▀█▀░█░░░█▀▀░█▀▀
# ░█░█░█░█░█░█░░█░░░█░░█░█░█▀▄░░░█▀▀░█▀▄░█░█░█▀▀░░█░░█░░░█▀▀░▀▀█
# ░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░▀▀▀░▀░▀░░░▀░░░▀░▀░▀▀▀░▀░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀
#

[[profile]]
name = "default"

    [[profile.output]]
    enable = true
    search = ["m=0x15E7", "s=", "v=Chimei Innolux Corporation"]
    mode = "1920x1080@60.001Hz"
    position = "960,2160"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

[[profile]]
name = "default-room"

    [[profile.output]]
    enable = true
    search = ["m=0x15E7", "s=", "v=Chimei Innolux Corporation"]
    mode = "1920x1080@60.001Hz"
    position = "960,2160"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

    [[profile.output]]
    enable = true
    search = ["m=L32p-30", "s=U5125YRF", "v=Lenovo Group Limited"]
    mode = "3840x2160@59.997Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

[[profile]]
name = "default-off"

    [[profile.output]]
    enable = false
    search = ["m=0x15E7", "s=", "v=Chimei Innolux Corporation"]
    mode = "1920x1080@60.001Hz"
    position = "960,2160"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

    [[profile.output]]
    enable = true
    search = ["m=L32p-30", "s=U5125YRF", "v=Lenovo Group Limited"]
    mode = "3840x2160@59.997Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false