[config]

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava || true'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.vencord]
input_path = '~/.config/matugen/templates/discord.theme'
output_path = '~/.config/vesktop/themes/matugen-theme.css'

[templates.obsidian-notecs]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/Code/notecs/.obsidian/snippets/matugne-theme.css'

[templates.obsidian-cmnplcbk]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/Code/cmnplcbk/.obsidian/snippets/matugne-theme.css'

[templates.kvantum]
input_path = '~/.config/matugen/templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = '~/.config/matugen/templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'
post_hook = 'kvantummanager --set matugen'

[templates.heroic]
input_path = '~/.config/matugen/templates/matugen-heroic.css'
output_path = '~/.config/heroic/themes/matugen-theme.css'

[templates.ghostty-tabs]
input_path = '~/.config/matugen/templates/ghostty-tab-top.css'
output_path = '~/.config/ghostty/matugen-theme.css'

[templates.ghostty-theme]
input_path = '~/.config/matugen/templates/ghostty-colors'
output_path = '~/.config/ghostty/matugen'

[templates.zen-userchrome]
input_path = '~/.config/matugen/templates/zen-userChrome.css'
output_path = '~/.zen/Profile.MaWe/chrome/userChrome.css'

[templates.zen-usercontent]
input_path = '~/.config/matugen/templates/zen-userContent.css'
output_path = '~/.zen/Profile.MaWe/chrome/userContent.css'

[templates.nvim]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-dark.lua'

[templates.nvimlight]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-light.lua'

[templates.pywal]
input_path = '~/.config/nvim/pywal/waltemplate'
output_path = '~/.cache/wal/colors'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.fastfetch]
input_path = '~/.config/matugen/templates/fast-fetch.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'

[templates.run_after-gtk]
input_path = '~/.config/matugen/templates/sample'
colors_to_compare = [
    { name = "blue", color = "#0000ff" },
    { name = "brown", color = "#a52a2a" },
    { name = "green", color = "#008000" },
    { name = "orange", color = "#ffa500" },
    { name = "pink", color = "#ffc0cb" },
    { name = "purple", color = "#800080" },
    { name = "red", color = "#ff0000" },
    { name = "slate", color = "#708090" },
    { name = "teal", color = "#008080" },
    { name = "yellow", color = "#ffff00" },
]
compare_to = "{{colors.primary.default.hex}}"
post_hook = 'ICON_THEME=Adwaita-{{closest_color}}; gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME && gtk4-update-icon-cache'

[templates.run_after-terminal]
input_path = '~/.config/matugen/templates/terminal-opening-colors.zsh.template'
output_path = "~/.config/zsh/opts/colors"

[templates.run_after-magick]
input_path = '~/.config/matugen/templates/sample'
pre_hook = 'magick {{image}} -gravity center -crop 1:1 -resize 150x150 $HOME/Pictures/wallpaper-square-nb.png &'
post_hook = 'source={{colors.source_color.default.hex}}; magick {{image}} -gravity center -crop 1:1 -resize 150x150 -bordercolor $source -border 12%x12% $HOME/Pictures/wallpaper-square.png &'

[templates.run_after-neo]
input_path = '~/.config/matugen/templates/neo-matrix-check.sh'
output_path = '~/.cache/neo-matrix.zsh'
post_hook = 'chmod +x ~/.cache/neo-matrix.zsh && ~/.cache/neo-matrix.zsh'

[config.custom_colors]
black            = "#000000"
red              = "#ff0000"
green            = "#00ff00"
yellow           = "#ffff00"
blue             = "#0000ff"
magenta          = "#ff00ff"
cyan             = "#00ffff"
white            = "#ffffff"

ansiBlack        = "#090300"
ansiRed          = "#db2d20"
ansiGreen        = "#01a252"
ansiYellow       = "#fded02"
ansiBlue         = "#01a0e4"
ansiMagenta      = "#a16a94"
ansiCyan         = "#b5e4f4"
ansiWhite        = "#a5a2a2"

ansiBrightBlack  = "#5c5855"
ansiBrightRed    = "#db2d20"
ansiBrightGreen  = "#01a252"
ansiBrightYellow = "#fded02"
ansiBrightBlue   = "#01a0e4"
ansiBrightMagenta= "#a16a94"
ansiBrightCyan   = "#b5e4f4"
ansiBrightWhite  = "#f7f7f7"
