#size	xhot	yhot	Path to PNG image	delay
16	8	14	bottom_tee/bottom_tee_000.png	40
20	10	17	bottom_tee/bottom_tee_001.png	40
22	11	19	bottom_tee/bottom_tee_002.png	40
24	12	21	bottom_tee/bottom_tee_003.png	40
28	14	25	bottom_tee/bottom_tee_004.png	40
32	16	28	bottom_tee/bottom_tee_005.png	40
40	20	35	bottom_tee/bottom_tee_006.png	40
48	24	43	bottom_tee/bottom_tee_007.png	40
56	28	50	bottom_tee/bottom_tee_008.png	40
64	32	57	bottom_tee/bottom_tee_009.png	40
72	36	64	bottom_tee/bottom_tee_010.png	40
80	40	71	bottom_tee/bottom_tee_011.png	40
88	44	79	bottom_tee/bottom_tee_012.png	40
96	48	86	bottom_tee/bottom_tee_013.png	40
