#size	xhot	yhot	Path to PNG image	delay
16	8	14	bottom_side/bottom_side_000.png	40
20	10	18	bottom_side/bottom_side_001.png	40
22	11	20	bottom_side/bottom_side_002.png	40
24	12	21	bottom_side/bottom_side_003.png	40
28	14	25	bottom_side/bottom_side_004.png	40
32	16	29	bottom_side/bottom_side_005.png	40
40	20	36	bottom_side/bottom_side_006.png	40
48	24	43	bottom_side/bottom_side_007.png	40
56	28	51	bottom_side/bottom_side_008.png	40
64	32	58	bottom_side/bottom_side_009.png	40
72	36	65	bottom_side/bottom_side_010.png	40
80	40	73	bottom_side/bottom_side_011.png	40
88	44	80	bottom_side/bottom_side_012.png	40
96	48	87	bottom_side/bottom_side_013.png	40
