#size	xhot	yhot	Path to PNG image	delay
16	14	14	bottom_right_corner/bottom_right_corner_000.png	40
20	17	18	bottom_right_corner/bottom_right_corner_001.png	40
22	19	19	bottom_right_corner/bottom_right_corner_002.png	40
24	21	21	bottom_right_corner/bottom_right_corner_003.png	40
28	25	25	bottom_right_corner/bottom_right_corner_004.png	40
32	28	29	bottom_right_corner/bottom_right_corner_005.png	40
40	35	36	bottom_right_corner/bottom_right_corner_006.png	40
48	42	43	bottom_right_corner/bottom_right_corner_007.png	40
56	50	50	bottom_right_corner/bottom_right_corner_008.png	40
64	57	58	bottom_right_corner/bottom_right_corner_009.png	40
72	64	65	bottom_right_corner/bottom_right_corner_010.png	40
80	71	72	bottom_right_corner/bottom_right_corner_011.png	40
88	78	79	bottom_right_corner/bottom_right_corner_012.png	40
96	85	87	bottom_right_corner/bottom_right_corner_013.png	40
