#size	xhot	yhot	Path to PNG image	delay
16	1	14	bottom_left_corner/bottom_left_corner_000.png	40
20	2	18	bottom_left_corner/bottom_left_corner_001.png	40
22	2	19	bottom_left_corner/bottom_left_corner_002.png	40
24	2	21	bottom_left_corner/bottom_left_corner_003.png	40
28	2	25	bottom_left_corner/bottom_left_corner_004.png	40
32	3	29	bottom_left_corner/bottom_left_corner_005.png	40
40	4	36	bottom_left_corner/bottom_left_corner_006.png	40
48	4	43	bottom_left_corner/bottom_left_corner_007.png	40
56	5	50	bottom_left_corner/bottom_left_corner_008.png	40
64	6	58	bottom_left_corner/bottom_left_corner_009.png	40
72	7	65	bottom_left_corner/bottom_left_corner_010.png	40
80	8	72	bottom_left_corner/bottom_left_corner_011.png	40
88	8	79	bottom_left_corner/bottom_left_corner_012.png	40
96	9	87	bottom_left_corner/bottom_left_corner_013.png	40
