#size	xhot	yhot	Path to PNG image	delay
16	7	1	center_ptr/center_ptr_000.png	40
20	9	1	center_ptr/center_ptr_001.png	40
22	10	1	center_ptr/center_ptr_002.png	40
24	11	1	center_ptr/center_ptr_003.png	40
28	13	1	center_ptr/center_ptr_004.png	40
32	15	2	center_ptr/center_ptr_005.png	40
40	19	2	center_ptr/center_ptr_006.png	40
48	23	3	center_ptr/center_ptr_007.png	40
56	27	3	center_ptr/center_ptr_008.png	40
64	31	4	center_ptr/center_ptr_009.png	40
72	35	4	center_ptr/center_ptr_010.png	40
80	39	5	center_ptr/center_ptr_011.png	40
88	43	5	center_ptr/center_ptr_012.png	40
96	47	6	center_ptr/center_ptr_013.png	40
