#size	xhot	yhot	Path to PNG image	delay
16	3	1	context-menu/context-menu_000.png	40
20	4	1	context-menu/context-menu_001.png	40
22	4	1	context-menu/context-menu_002.png	40
24	5	1	context-menu/context-menu_003.png	40
28	6	1	context-menu/context-menu_004.png	40
32	7	2	context-menu/context-menu_005.png	40
40	8	2	context-menu/context-menu_006.png	40
48	10	3	context-menu/context-menu_007.png	40
56	12	3	context-menu/context-menu_008.png	40
64	14	4	context-menu/context-menu_009.png	40
72	16	4	context-menu/context-menu_010.png	40
80	17	5	context-menu/context-menu_011.png	40
88	19	5	context-menu/context-menu_012.png	40
96	21	6	context-menu/context-menu_013.png	40
