#size	xhot	yhot	Path to PNG image	delay
16	8	8	crossed_circle/crossed_circle_000.png	40
20	10	10	crossed_circle/crossed_circle_001.png	40
22	11	11	crossed_circle/crossed_circle_002.png	40
24	12	12	crossed_circle/crossed_circle_003.png	40
28	14	14	crossed_circle/crossed_circle_004.png	40
32	16	16	crossed_circle/crossed_circle_005.png	40
40	20	20	crossed_circle/crossed_circle_006.png	40
48	24	24	crossed_circle/crossed_circle_007.png	40
56	28	28	crossed_circle/crossed_circle_008.png	40
64	32	32	crossed_circle/crossed_circle_009.png	40
72	36	36	crossed_circle/crossed_circle_010.png	40
80	40	40	crossed_circle/crossed_circle_011.png	40
88	44	44	crossed_circle/crossed_circle_012.png	40
96	48	48	crossed_circle/crossed_circle_013.png	40
