#size	xhot	yhot	Path to PNG image	delay
16	6	4	dnd_no_drop/dnd_no_drop_000.png	40
20	7	5	dnd_no_drop/dnd_no_drop_001.png	40
22	8	5	dnd_no_drop/dnd_no_drop_002.png	40
24	9	6	dnd_no_drop/dnd_no_drop_003.png	40
28	10	7	dnd_no_drop/dnd_no_drop_004.png	40
32	12	8	dnd_no_drop/dnd_no_drop_005.png	40
40	15	10	dnd_no_drop/dnd_no_drop_006.png	40
48	18	12	dnd_no_drop/dnd_no_drop_007.png	40
56	21	14	dnd_no_drop/dnd_no_drop_008.png	40
64	25	16	dnd_no_drop/dnd_no_drop_009.png	40
72	28	18	dnd_no_drop/dnd_no_drop_010.png	40
80	31	20	dnd_no_drop/dnd_no_drop_011.png	40
88	34	22	dnd_no_drop/dnd_no_drop_012.png	40
96	37	24	dnd_no_drop/dnd_no_drop_013.png	40
