#size	xhot	yhot	Path to PNG image	delay
16	8	8	fd_double_arrow/fd_double_arrow_000.png	40
20	10	10	fd_double_arrow/fd_double_arrow_001.png	40
22	11	11	fd_double_arrow/fd_double_arrow_002.png	40
24	12	12	fd_double_arrow/fd_double_arrow_003.png	40
28	14	14	fd_double_arrow/fd_double_arrow_004.png	40
32	16	16	fd_double_arrow/fd_double_arrow_005.png	40
40	20	20	fd_double_arrow/fd_double_arrow_006.png	40
48	24	24	fd_double_arrow/fd_double_arrow_007.png	40
56	28	28	fd_double_arrow/fd_double_arrow_008.png	40
64	32	32	fd_double_arrow/fd_double_arrow_009.png	40
72	36	36	fd_double_arrow/fd_double_arrow_010.png	40
80	40	40	fd_double_arrow/fd_double_arrow_011.png	40
88	44	44	fd_double_arrow/fd_double_arrow_012.png	40
96	48	48	fd_double_arrow/fd_double_arrow_013.png	40
