#size	xhot	yhot	Path to PNG image	delay
16	1	8	left_side/left_side_000.png	40
20	1	10	left_side/left_side_001.png	40
22	1	11	left_side/left_side_002.png	40
24	1	12	left_side/left_side_003.png	40
28	2	14	left_side/left_side_004.png	40
32	2	16	left_side/left_side_005.png	40
40	3	20	left_side/left_side_006.png	40
48	3	24	left_side/left_side_007.png	40
56	4	28	left_side/left_side_008.png	40
64	5	32	left_side/left_side_009.png	40
72	5	36	left_side/left_side_010.png	40
80	6	40	left_side/left_side_011.png	40
88	7	44	left_side/left_side_012.png	40
96	7	48	left_side/left_side_013.png	40
