#size	xhot	yhot	Path to PNG image	delay
16	2	5	question_arrow/question_arrow_000.png	40
20	3	6	question_arrow/question_arrow_001.png	40
22	3	7	question_arrow/question_arrow_002.png	40
24	3	8	question_arrow/question_arrow_003.png	40
28	4	9	question_arrow/question_arrow_004.png	40
32	5	10	question_arrow/question_arrow_005.png	40
40	6	13	question_arrow/question_arrow_006.png	40
48	7	16	question_arrow/question_arrow_007.png	40
56	9	18	question_arrow/question_arrow_008.png	40
64	10	21	question_arrow/question_arrow_009.png	40
72	11	24	question_arrow/question_arrow_010.png	40
80	13	26	question_arrow/question_arrow_011.png	40
88	14	29	question_arrow/question_arrow_012.png	40
96	15	32	question_arrow/question_arrow_013.png	40
