#size	xhot	yhot	Path to PNG image	delay
16	1	8	right_tee/right_tee_000.png	40
20	2	10	right_tee/right_tee_001.png	40
22	2	11	right_tee/right_tee_002.png	40
24	2	12	right_tee/right_tee_003.png	40
28	3	14	right_tee/right_tee_004.png	40
32	3	16	right_tee/right_tee_005.png	40
40	4	20	right_tee/right_tee_006.png	40
48	5	24	right_tee/right_tee_007.png	40
56	6	28	right_tee/right_tee_008.png	40
64	7	32	right_tee/right_tee_009.png	40
72	8	36	right_tee/right_tee_010.png	40
80	9	40	right_tee/right_tee_011.png	40
88	9	44	right_tee/right_tee_012.png	40
96	10	48	right_tee/right_tee_013.png	40
