#size	xhot	yhot	Path to PNG image	delay
16	12	1	right_ptr/right_ptr_000.png	40
20	15	1	right_ptr/right_ptr_001.png	40
22	17	1	right_ptr/right_ptr_002.png	40
24	19	1	right_ptr/right_ptr_003.png	40
28	22	1	right_ptr/right_ptr_004.png	40
32	25	2	right_ptr/right_ptr_005.png	40
40	31	2	right_ptr/right_ptr_006.png	40
48	38	3	right_ptr/right_ptr_007.png	40
56	44	3	right_ptr/right_ptr_008.png	40
64	51	4	right_ptr/right_ptr_009.png	40
72	57	4	right_ptr/right_ptr_010.png	40
80	63	5	right_ptr/right_ptr_011.png	40
88	70	5	right_ptr/right_ptr_012.png	40
96	76	6	right_ptr/right_ptr_013.png	40
