#size	xhot	yhot	Path to PNG image	delay
16	14	8	right_side/right_side_000.png	40
20	18	10	right_side/right_side_001.png	40
22	20	11	right_side/right_side_002.png	40
24	21	12	right_side/right_side_003.png	40
28	25	14	right_side/right_side_004.png	40
32	29	16	right_side/right_side_005.png	40
40	36	20	right_side/right_side_006.png	40
48	43	24	right_side/right_side_007.png	40
56	50	28	right_side/right_side_008.png	40
64	58	32	right_side/right_side_009.png	40
72	65	36	right_side/right_side_010.png	40
80	72	40	right_side/right_side_011.png	40
88	80	44	right_side/right_side_012.png	40
96	87	48	right_side/right_side_013.png	40
