#size	xhot	yhot	Path to PNG image	delay
16	8	13	sb_down_arrow/sb_down_arrow_000.png	40
20	10	17	sb_down_arrow/sb_down_arrow_001.png	40
22	11	19	sb_down_arrow/sb_down_arrow_002.png	40
24	12	20	sb_down_arrow/sb_down_arrow_003.png	40
28	14	24	sb_down_arrow/sb_down_arrow_004.png	40
32	16	27	sb_down_arrow/sb_down_arrow_005.png	40
40	20	34	sb_down_arrow/sb_down_arrow_006.png	40
48	24	41	sb_down_arrow/sb_down_arrow_007.png	40
56	28	48	sb_down_arrow/sb_down_arrow_008.png	40
64	32	55	sb_down_arrow/sb_down_arrow_009.png	40
72	36	62	sb_down_arrow/sb_down_arrow_010.png	40
80	40	69	sb_down_arrow/sb_down_arrow_011.png	40
88	44	76	sb_down_arrow/sb_down_arrow_012.png	40
96	48	83	sb_down_arrow/sb_down_arrow_013.png	40
