#size	xhot	yhot	Path to PNG image	delay
16	13	8	sb_right_arrow/sb_right_arrow_000.png	40
20	17	10	sb_right_arrow/sb_right_arrow_001.png	40
22	19	11	sb_right_arrow/sb_right_arrow_002.png	40
24	20	12	sb_right_arrow/sb_right_arrow_003.png	40
28	24	14	sb_right_arrow/sb_right_arrow_004.png	40
32	27	16	sb_right_arrow/sb_right_arrow_005.png	40
40	34	20	sb_right_arrow/sb_right_arrow_006.png	40
48	41	24	sb_right_arrow/sb_right_arrow_007.png	40
56	48	28	sb_right_arrow/sb_right_arrow_008.png	40
64	55	32	sb_right_arrow/sb_right_arrow_009.png	40
72	62	36	sb_right_arrow/sb_right_arrow_010.png	40
80	69	40	sb_right_arrow/sb_right_arrow_011.png	40
88	76	44	sb_right_arrow/sb_right_arrow_012.png	40
96	83	48	sb_right_arrow/sb_right_arrow_013.png	40
