#size	xhot	yhot	Path to PNG image	delay
16	14	1	top_right_corner/top_right_corner_000.png	40
20	17	1	top_right_corner/top_right_corner_001.png	40
22	19	2	top_right_corner/top_right_corner_002.png	40
24	21	2	top_right_corner/top_right_corner_003.png	40
28	25	2	top_right_corner/top_right_corner_004.png	40
32	28	3	top_right_corner/top_right_corner_005.png	40
40	35	3	top_right_corner/top_right_corner_006.png	40
48	42	4	top_right_corner/top_right_corner_007.png	40
56	50	5	top_right_corner/top_right_corner_008.png	40
64	57	6	top_right_corner/top_right_corner_009.png	40
72	64	6	top_right_corner/top_right_corner_010.png	40
80	71	7	top_right_corner/top_right_corner_011.png	40
88	78	8	top_right_corner/top_right_corner_012.png	40
96	85	9	top_right_corner/top_right_corner_013.png	40
