#size	xhot	yhot	Path to PNG image	delay
16	1	1	top_left_corner/top_left_corner_000.png	40
20	2	1	top_left_corner/top_left_corner_001.png	40
22	2	2	top_left_corner/top_left_corner_002.png	40
24	2	2	top_left_corner/top_left_corner_003.png	40
28	3	2	top_left_corner/top_left_corner_004.png	40
32	3	3	top_left_corner/top_left_corner_005.png	40
40	4	3	top_left_corner/top_left_corner_006.png	40
48	5	4	top_left_corner/top_left_corner_007.png	40
56	6	5	top_left_corner/top_left_corner_008.png	40
64	7	6	top_left_corner/top_left_corner_009.png	40
72	8	6	top_left_corner/top_left_corner_010.png	40
80	9	7	top_left_corner/top_left_corner_011.png	40
88	9	8	top_left_corner/top_left_corner_012.png	40
96	10	9	top_left_corner/top_left_corner_013.png	40
