#size	xhot	yhot	Path to PNG image	delay
16	8	8	vertical-text/vertical-text_000.png	40
20	10	10	vertical-text/vertical-text_001.png	40
22	11	11	vertical-text/vertical-text_002.png	40
24	12	12	vertical-text/vertical-text_003.png	40
28	14	14	vertical-text/vertical-text_004.png	40
32	16	16	vertical-text/vertical-text_005.png	40
40	20	20	vertical-text/vertical-text_006.png	40
48	24	24	vertical-text/vertical-text_007.png	40
56	28	28	vertical-text/vertical-text_008.png	40
64	32	32	vertical-text/vertical-text_009.png	40
72	36	36	vertical-text/vertical-text_010.png	40
80	40	40	vertical-text/vertical-text_011.png	40
88	44	44	vertical-text/vertical-text_012.png	40
96	48	48	vertical-text/vertical-text_013.png	40
