#!/bin/bash

export BW_PASSWD=$(secret-tool lookup email mahmoodathil@proton.me service bitwarden profile personal)

session=""
while [[ -z "$session" ]]; do
    session=$(bw unlock --raw --passwordenv BW_PASSWD)
    if [[ $? -ne 0 ]]; then
        echo "Command failed"
        continue
    fi
done
echo "Secret set and BW session established!"

export BW_SESSION=$session
