#!      ░▒▒▒░░░▓▓           ___________
#!    ░░▒▒▒░░░░░▓▓        //___________/
#!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#!       ░▒▓▓   ▓▓  //____/

# $LOCKSCREEN = hyprlock # preferred LOCKSCREEN e.g swaylock

general {

    lock_cmd = killall hyprlock || hyprlock -q
    unlock_cmd = killall -q -s SIGUSR1 hyprlock

    before_sleep_cmd = hyprlock; sleep 2    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on; bash -c /home/madwayl/.config/hypr/scripts/hyprlock-tty-unknown.sh  # to avoid having to press a key twice to turn on the display.

    ignore_dbus_inhibit = false
    inhibit_sleep = 1
}

# Lock it first before dpms off so that screen won't show for a moment after wake up.
listener {
    timeout = 630
    on-timeout = hyprlock
    on-resume = bash -c /home/madwayl/.config/hypr/scripts/hyprlock-tty-unknown.sh
}

# Dims the display
listener {
    timeout = 830
    on-timeout = { brightnessctl -s && brightnessctl s 1%; }
    on-resume = brightnessctl -r
}

# DPMS off
listener {
    timeout = 1050
    on-timeout = hyprctl dispatch dpms off #do not turn off display while media is playing
    on-resume = hyprctl dispatch dpms on; bash -c /home/madwayl/.config/hypr/scripts/hyprlock-tty-unknown.sh
}

# Suspend
listener {
    timeout = 1500
    on-timeout = systemctl suspend
    on-resume = bash -c /home/madwayl/.config/hypr/scripts/hyprlock-tty-unknown.sh
}

# hyprlang noerror true
# Source anything  from this path if you want to add your own listener
# source command actually do not exist yet
# source = ~/.config/hypridle/*
# hyprlang noerror false
