# hyprlang noerror true
exec-once = hyprpm reload

source = ./init.conf
source = ./themes/theme.conf # theme specific settings
source = ./animations.conf   # source animations variables

# hyprlang noerror false
exec-once = waybar &

source = ./monitors.conf    # Monitor configuration
source = ./inputs.conf      # Input configuration
source = ./keybindings.conf # Keyboard shortcuts
source = ./windowrules.conf # Window rules
source = ./workflows.conf   # workflows configuration overrides everything
source = ./workspaces.conf  # workspace configuration
