[preferred]
default=gnome;
org.freedesktop.impl.portal.Access=gnome;
org.freedesktop.impl.portal.Notification=gnome;
org.freedesktop.impl.portal.Secret=gnome-keyring;
org.freedesktop.impl.portal.FileChooser=gnome;
org.freedesktop.impl.portal.ScreenCast=gnome;