/**
 * @name system24 (vencord)
 * @description a tui-style discord theme. based on https://github.com/nanoqoi/vencord-theme.
 * @author refact0r
 * @version 2.0.0
 * @invite nz87hXyvcy
 * @website https://github.com/refact0r/system24
 * @source https://github.com/refact0r/system24/blob/master/theme/system24-vencord.theme.css
 * @authorId 508863359777505290
 * @authorLink https://www.refact0r.dev
*/

/* import theme modules */
@import url('https://refact0r.github.io/system24/build/system24.css');

body {
    font-weight: 300; /* text font weight. 300 is light, 400 is normal. DOES NOT AFFECT BOLD TEXT */
    letter-spacing: -0.05ch; /* decreases letter spacing for better readability. recommended on monospace fonts.*/

    /* sizes */
    --gap: 12px; /* spacing between panels */
    --divider-thickness: 4px; /* thickness of unread messages divider and highlighted message borders */
    --border-thickness: 2px; /* thickness of borders around main panels. DOES NOT AFFECT OTHER BORDERS */
    --border-hover-transition: 0.2s ease; /* transition for borders when hovered */

    /* animation/transition options */
    --animations: on; /* off: disable animations/transitions, on: enable animations/transitions */
    --list-item-transition: 0.2s ease; /* transition for list items */
    --dms-icon-svg-transition: 0.4s ease; /* transition for the dms icon */

    /* top bar options */
    --top-bar-height: var(--gap); /* height of the top bar (discord default is 36px, old discord style is 24px, var(--gap) recommended if button position is set to titlebar) */
    --top-bar-button-position: titlebar; /* off: default position, hide: hide buttons completely, serverlist: move inbox button to server list, titlebar: move inbox button to channel titlebar (will hide title) */
    --top-bar-title-position: off; /* off: default centered position, hide: hide title completely, left: left align title (like old discord) */
    --subtle-top-bar-title: off; /* off: default, on: hide the icon and use subtle text color (like old discord) */

    /* window controls */
    --custom-window-controls: off; /* off: default window controls, on: custom window controls */
    --window-control-size: 14px; /* size of custom window controls */

    /* dms button options */
    --custom-dms-icon: custom; /* off: use default discord icon, hide: remove icon entirely, custom: use custom icon */
    --dms-icon-svg-url: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 27 27' width='24' height='24'%3E%3Cpath fill='currentColor' d='M0 0h7v1H6v1H5v1H4v1H3v1H2v1h5v1H0V6h1V5h1V4h1V3h1V2h1V1H0m13 2h5v1h-1v1h-1v1h-1v1h3v1h-5V7h1V6h1V5h1V4h-3m8 5h1v5h1v-1h1v1h-1v1h1v-1h1v1h-1v3h-1v1h-2v1h-1v1h1v-1h2v-1h1v2h-1v1h-2v1h-1v-1h-1v1h-6v-1h-1v-1h-1v-2h1v1h2v1h3v1h1v-1h-1v-1h-3v-1h-4v-4h1v-2h1v-1h1v-1h1v2h1v1h1v-1h1v1h-1v1h2v-2h1v-2h1v-1h1M8 14h2v1H9v4h1v2h1v1h1v1h1v1h4v1h-6v-1H5v-1H4v-5h1v-1h1v-2h2m17 3h1v3h-1v1h-1v1h-1v2h-2v-2h2v-1h1v-1h1m1 0h1v3h-1v1h-2v-1h1v-1h1'%3E%3C/path%3E%3C/svg%3E"); /* icon svg url. MUST BE A SVG. */
    --dms-icon-svg-size: 90%; /* size of the svg (css mask-size property) */
    --dms-icon-color-before: var(--fg-color); /* normal icon color */
    --dms-icon-color-after: var(--accent-color); /* icon color when button is hovered/selected */
    --custom-dms-background: off; /* off to disable, image to use a background image (must set url variable below), color to use a custom color/gradient */
    --dms-background-image-url: url(''); /* url of the background image */
    --dms-background-image-size: cover; /* size of the background image (css background-size property) */
    --dms-background-color: linear-gradient(70deg, var(--color-2), var(--color-3), var(--color-4)); /* fixed color/gradient (css background property) */

    /* background image options */
    --background-image: off; /* off: no background image, on: enable background image (must set url variable below) */
    --background-image-url: url(''); /* url of the background image */

    /* transparency/blur options */
    /* NOTE: TO USE TRANSPARENCY/BLUR, YOU MUST HAVE TRANSPARENT BG COLORS. FOR EXAMPLE: --bg-4: hsla(220, 15%, 10%, 0.7); */
    --transparency-tweaks: off; /* off: no changes, on: remove some elements for better transparency */
    --remove-bg-layer: off; /* off: no changes, on: remove the base --bg-3 layer for use with window transparency (WILL OVERRIDE BACKGROUND IMAGE) */
    --panel-blur: off; /* off: no changes, on: blur the background of panels */
    --blur-amount: 12px; /* amount of blur */
    --bg-floating: var(--bg-color); /* set this to a more opaque color if floating panels look too transparent. only applies if panel blur is on  */

    /* other options */
    --small-user-panel: on; /* off: default user panel, on: smaller user panel like in old discord */

    /* unrounding options */
    --unrounding: on; /* off: default, on: remove rounded corners from panels */

    /* styling options */
    --custom-spotify-bar: on; /* off: default, on: custom text-like spotify progress bar */
    --ascii-titles: on; /* off: default, on: use ascii font for titles at the start of a channel */
    --ascii-loader: system24; /* off: default, system24: use system24 ascii loader, cats: use cats loader */

    /* panel labels */
    --panel-labels: on; /* off: default, on: add labels to panels */
    --label-color: var(--fg-color); /* color of labels */
    --label-font-weight: 500; /* font weight of labels */
}

/* color options */
:root {
    --colors: on; /* off: discord default colors, on: midnight custom colors */

    /* matugen color palette */
    --fg-color: {{colors.on_surface.dark.hex}};
    --bg-color: {{colors.surface.dark.hex}};
    --accent-color: {{colors.primary.dark.hex}};
    --color-2: {{colors.secondary.dark.hex}};
    --color-3: {{colors.tertiary.dark.hex}};
    --color-4: {{colors.primary_container.dark.hex}};
    --color-5: {{colors.secondary_container.dark.hex}};
    --color-6: {{colors.error.dark.hex}};

    /* text colors */
    --text-0: var(--fg-color); /* text on colored elements */
    --text-1: var(--accent-color); /* bright text on colored elements */
    --text-2: var(--fg-color); /* headings and important text */
    --text-3: var(--fg-color); /* normal text */
    --text-4: var(--fg-color); /* icon buttons and channels */
    --text-5: {{colors.on_surface_variant.dark.hex}}; /* muted channels/chats and timestamps */

    /* background and dark colors */
    --bg-1: {{colors.surface_container_highest.dark.hex}}; /* dark buttons when clicked */
    --bg-2: {{colors.surface_container_high.dark.hex}}; /* dark buttons */
    --bg-3: {{colors.surface_container.dark.hex}}; /* spacing, secondary elements */
    --bg-4: {{colors.surface.dark.hex}}; /* main background color */
    --hover: {{colors.on_surface.dark.hex}}14; /* channels and buttons when hovered */
    --active: {{colors.on_surface.dark.hex}}1f; /* channels and buttons when clicked or selected */
    --active-2: {{colors.on_surface.dark.hex}}29; /* extra state for transparent buttons */
    --message-hover: {{colors.on_surface.dark.hex}}0a; /* messages when hovered */

    /* accent colors */
    --accent-1: var(--accent-color); /* links and other accent text */
    --accent-2: var(--color-2); /* small accent elements */
    --accent-3: var(--color-3); /* accent buttons */
    --accent-4: var(--color-4); /* accent buttons when hovered */
    --accent-5: var(--color-5); /* accent buttons when clicked */
    --accent-new: var(--color-6); /* stuff that's normally red like mute/deafen buttons */
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-color), transparent 90%) 40%, transparent); /* background of messages that mention you */
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-color), transparent 95%) 40%, transparent); /* background of messages that mention you when hovered */
    --reply: linear-gradient(to right, color-mix(in hsl, var(--fg-color), transparent 90%) 40%, transparent); /* background of messages that reply to you */
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--fg-color), transparent 95%) 40%, transparent); /* background of messages that reply to you when hovered */

    /* status indicator colors */
    --online: {{colors.tertiary.dark.hex}}; /* change to #43a25a for default */
    --dnd: {{colors.error.dark.hex}}; /* change to #d83a42 for default */
    --idle: {{colors.secondary.dark.hex}}; /* change to #ca9654 for default */
    --streaming: {{colors.primary.dark.hex}}; /* change to #593695 for default */
    --offline: {{colors.outline.dark.hex}}; /* change to #83838b for default offline color */

    /* border colors */
    --border-light: {{colors.outline_variant.dark.hex}}33; /* general light border color */
    --border: {{colors.outline_variant.dark.hex}}4d; /* general normal border color */
    --border-hover: {{colors.surface_container_high.default.hex}}; /* border color of panels when hovered */
    --button-border: {{colors.outline_variant.dark.hex}}1a; /* neutral border color of buttons */
}


body {
    --font: "Rec Mono Linear" !important;
    --code-font: "Recursive Mono Linear Static" !important;

    --gap: 6px;
    --unrounding: off;
    --custom-window-control: off;
    --window-control-size: 0px;
    --panel-blur: on;
    --blur-amount: 12px;
    --small-user-panel: on;
    --panel-labels: off;
    --blur-amount: 12px; /* amount of blur */
    --bg-floating: var(
        --bg-3
    ); /* set this to a more opaque color if floating panels look too transparent. only applies if panel blur is on  */
    --border-thickness: 4px; /* thickness of borders around main panels. DOES NOT AFFECT OTHER BORDERS */
    --border-hover-transition: 0.8s ease; /* transition for borders when hovered */


	/* amount of spacing and padding */
    --spacing-4: 4px;
    --spacing-8: 5px;
    --spacing-12: 6px;
    --spacing-16: 8px;

    --radius-none: 0px;
    --radius-xxs: 2px;
    --radius-xs: 4px;
    --radius-sm: var(--radius-xs);
    --radius-md: 6px;
    --radius-lg: 6px;
    --radius-xl: 8px;
    --radius-xxl: 12;


    /* base colors */
    --red-1: oklch(75% 0.13 0);
    --red-2: oklch(70% 0.13 0);
    --red-3: oklch(65% 0.13 0);
    --red-4: oklch(60% 0.13 0);
    --red-5: oklch(55% 0.13 0);

    --green-1: oklch(75% 0.12 170);
    --green-2: oklch(70% 0.12 170);
    --green-3: oklch(65% 0.12 170);
    --green-4: oklch(60% 0.12 170);
    --green-5: oklch(55% 0.12 160);

    --blue-1: oklch(75% 0.11 215);
    --blue-2: oklch(70% 0.11 215);
    --blue-3: oklch(65% 0.11 215);
    --blue-4: oklch(60% 0.11 215);
    --blue-5: oklch(55% 0.11 215);

    --yellow-1: oklch(80% 0.12 90);
    --yellow-2: oklch(75% 0.12 90);
    --yellow-3: oklch(70% 0.12 90);
    --yellow-4: oklch(65% 0.12 90);
    --yellow-5: oklch(60% 0.12 90);

    --purple-1: oklch(75% 0.12 310);
    --purple-2: oklch(70% 0.12 310);
    --purple-3: oklch(65% 0.12 310);
    --purple-4: oklch(60% 0.12 310);
    --purple-5: oklch(55% 0.12 310);

    --bg-4: rgba(0, 0, 0, 0.7);
    --text-0: {{colors.on_primary.dark.hex}};

}

.container__5e434, .container__01ae2 {
    background-color: {{colors.surface_container_high.default.hex}} !important;
}

h3[data-text-variant='heading-xxl/extrabold'] {
        font-family: var(--font);
        font-size: 40px;
        font-weight: 800;
    }

.content_a2f514 {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 32px;
        position: static;
    }
    .content_a2f514 > .spinner_a2f514 {
        display: none;
    }
    .content_a2f514::before {
        display: block;
        content: url('https://raw.githubusercontent.com/refact0r/system24/refs/heads/main/assets/cats.gif');
    }
    .text_a2f514 {
        position: static;
    }
