/**
 * @name Matugen
 * @description A Matugen-Customized discord theme.
 * @author ass
*/

/* IMPORTANT: make sure to enable dark mode in discord settings for the theme to apply properly!!! */

@import url('https://refact0r.github.io/system24/build/system24.css');

:root {
    --font: "Google Sans Code NF" !important;
    --code-font: "Google Sans Code NF" !important;

/* customize things here */

	/* top left corner text */
	--corner-text: 'Midnight';

	/* color of status indicators and window controls */
    --online-indicator: {{colors.inverse_primary.default.hex}};     /* change to #23a55a for default green */
	--dnd-indicator: {{colors.error.default.hex}};                  /* change to #f13f43 for default red */
	--idle-indicator: {{colors.tertiary_container.default.hex}};    /* change to #f0b232 for default yellow */
	--streaming-indicator: {{colors.on_primary.default.hex}};       /* change to #593695 for default purple */

	/* accent colors */
    --accent-1: {{colors.tertiary.default.hex}};            /* links */
	--accent-2: {{colors.primary.default.hex}};             /* general unread/mention elements, some icons when active */
	--accent-3: {{colors.primary.default.hex}};             /* accent buttons */
	--accent-4: {{colors.surface_bright.default.hex}};      /* accent buttons when hovered */
	--accent-5: {{colors.primary_fixed_dim.default.hex}};   /* accent buttons when clicked */
	--mention:  {{colors.surface.default.hex}};             /* mentions & mention messages */
	--mention-hover: {{colors.surface_bright.default.hex}}; /* mentions & mention messages when hovered */

	/* text colors */
	--text-0: {{colors.surface.default.hex}};               /* text on colored elements */
	--text-1: {{colors.on_surface.default.hex}};            /* other normally white text */
	--text-2: {{colors.on_surface.default.hex}};            /* headings and important text */
	--text-3: {{colors.on_surface_variant.default.hex}};    /* normal text */
	--text-4: {{colors.on_surface_variant.default.hex}};    /* icon buttons and channels */
	--text-5: {{colors.outline.default.hex}};               /* muted channels/chats and timestamps */

	/* background and dark colors */
    --bg-1: {{colors.primary.default.hex}};                             /* dark buttons when clicked */
	--bg-2: {{colors.surface_container_high.default.hex}};              /* dark buttons */
	--bg-3: {{colors.surface_container_low.default.hex}};               /* spacing, secondary elements */
	--bg-4: {{colors.surface.default.hex}};                             /* main background color */
	--hover: {{colors.surface_bright.default.hex}};                     /* channels and buttons when hovered */
	--active: {{colors.surface_bright.default.hex}};                    /* channels and buttons when clicked or selected */
	--message-hover: {{colors.surface_bright.default.hex}};             /* messages when hovered */

	/* amount of spacing and padding */
    --spacing-4: 4px;
    --spacing-8: 5px;
    --spacing-12: 6px;
    --spacing-16: 8px;

    --radius-none: 0px;
    --radius-xxs: 2px;
    --radius-xs: 4px;
    --radius-sm: var(--radius-xs);
    --radius-md: 6px;
    --radius-lg: 6px;
    --radius-xl: 8px;
    --radius-xxl: 12;

    /* animations */
    /* ALL ANIMATIONS CAN BE DISABLED WITH REDUCED MOTION IN DISCORD SETTINGS */
    --list-item-transition: 0.2s ease; /* channels/members/settings hover transition */
    --unread-bar-transition: 0.2s ease; /* unread bar moving into view transition */
    --moon-spin-transition: 0.4s ease; /* moon icon spin */
    --icon-spin-transition: 1s ease; /* round icon button spin (settings, emoji, etc.) */
	/* direct messages moon icon */
	/* change to block to show, none to hide */
	--discord-icon: none; /* discord icon */
	--moon-icon: block; /* moon icon */
	--moon-icon-url: url('https://upload.wikimedia.org/wikipedia/commons/c/c4/Font_Awesome_5_solid_moon.svg'); /* custom icon url */
	--moon-icon-size: auto;

	/* filter uncolorable elements to fit theme */
	/* (just set to none, they're too much work to configure) */
	--login-bg-filter: saturate(0.3) hue-rotate(-15deg) brightness(0.4); /* login background artwork */
	--green-to-accent-3-filter: hue-rotate(56deg) saturate(1.43); /* add friend page explore icon */
	--blurple-to-accent-3-filter: hue-rotate(304deg) saturate(0.84) brightness(1.2); /* add friend page school icon */
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 90%) 40%, transparent); /* background of messages that mention you */
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 95%) 40%, transparent); /* background of messages that mention you when hovered */
    --reply: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 90%) 40%, transparent); /* background of messages that reply to you */
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 95%) 40%, transparent); /* background of messages that reply to you when hovered */

    /* status indicator colors */
    --online: var(--green-2); /* change to #40a258 for default */
    --dnd: var(--red-2); /* change to #d83a41 for default */
    --idle: var(--yellow-2); /* change to #cc954c for default */
    --streaming: var(--purple-2); /* change to ##9147ff for default */
    --offline: var(--text-4); /* change to #82838b for default offline color */

    /* border colors */
    --border-light: var(--hover); /* general light border color */
    --border: var(--active); /* general normal border color */
    --border-hover: var(--accent-2); /* border color of panels when hovered */
    --button-border: hsl(220, 0%, 100%, 0.1); /* neutral border color of buttons */

    /* base colors */
    --red-1: oklch(75% 0.13 0);
    --red-2: oklch(70% 0.13 0);
    --red-3: oklch(65% 0.13 0);
    --red-4: oklch(60% 0.13 0);
    --red-5: oklch(55% 0.13 0);

    --green-1: oklch(75% 0.12 170);
    --green-2: oklch(70% 0.12 170);
    --green-3: oklch(65% 0.12 170);
    --green-4: oklch(60% 0.12 170);
    --green-5: oklch(55% 0.12 160);

    --blue-1: oklch(75% 0.11 215);
    --blue-2: oklch(70% 0.11 215);
    --blue-3: oklch(65% 0.11 215);
    --blue-4: oklch(60% 0.11 215);
    --blue-5: oklch(55% 0.11 215);

    --yellow-1: oklch(80% 0.12 90);
    --yellow-2: oklch(75% 0.12 90);
    --yellow-3: oklch(70% 0.12 90);
    --yellow-4: oklch(65% 0.12 90);
    --yellow-5: oklch(60% 0.12 90);

    --purple-1: oklch(75% 0.12 310);
    --purple-2: oklch(70% 0.12 310);
    --purple-3: oklch(65% 0.12 310);
    --purple-4: oklch(60% 0.12 310);
    --purple-5: oklch(55% 0.12 310);
}

/* Selected chat/friend text */
.selected_f5eb4b,
.selected_f6f816 .link_d8bfb3 {
  color: var(--text-0) !important;
  background: var(--accent-3) !important;
}

.selected_f6f816 .link_d8bfb3 * {
  color: var(--text-0) !important;
  fill: var(--text-0) !important;
}

body {
    --gap: 8px;
    --unrounding: off;
    --custom-window-control: on;
    --window-control-size: 0px;
    --panel-blur: on;
    --blur-amount: 12px;
    --small-user-panel: off;
    --panel-labels: off;
    --blur-amount: 12px; /* amount of blur */
    --bg-floating: var(
        --bg-3
    ); /* set this to a more opaque color if floating panels look too transparent. only applies if panel blur is on  */
    --border-thickness: 1px; /* thickness of borders around main panels. DOES NOT AFFECT OTHER BORDERS */
    --border-hover-transition: 0.8s ease; /* transition for borders when hovered */
}
